remote_theme: fongandrew/hydeout
markdown: kramdown
highlighter: rouge

title: "David Tavarez"
tagline: "Coding for fun and profit!"
url: https://davidtavarez.github.io/
description: "Software Developer and Privacy Freak."

author:
  name: "David Tavarez"
  url: https://twitter.com/davidtavarez

plugins:
 - jekyll-feed
 - jekyll-gist
 - jekyll-paginate
 
paginate: 5
show_excerpts: true

version: 30

disqus:
  shortname: david-tavarezs-blog
