theme: minima

twitter_username: davidtavarez
github_username:  davidtavarez
linkedin_username: davidtavarez

rss: rss

minima:
  date_format: "%b %-d, %Y"

title: Software, Privacy, Security, Code and Fun!
author: davidtavarez
email: david@punksec.com
description: > 
  I'm a security and privacy freak, Linux lover and a pentester enthusiast. I like to be
  challenged and my focus is to be as productive as I can. I code since I was a kid and I'm a better
  baller than a coder, at least that I want to believe. I'm highly entrepreneurial and efficient at
  building and maintaining high quality software.
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
show_excerpts: false
