theme: minima

github_username:  davidtavarez
linkedin_username: davidtavarez

minima:
  date_format: "%b %-d, %Y"

title: David Tavárez
author: davidtavarez
email: david@punksec.com
description: > 
  Security and privacy freak, Linux user and a Pentester enthusiast. I've been coding since I was a kid and I'm a better baller than a coder, at least I want to believe that.
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
show_excerpts: true
