remote_theme: fongandrew/hydeout

title:  'I\'m David'
tagline: 'A Jekyll theme'
url: https://fongandrew.github.io
description: 'Software engineer, Security and privacy freak and a Pentester enthusiast. I've been coding since I was a kid and I'm a better baller than a developer.'

author:
  name: 'David Tavarez'
  url: https://twitter.com/davidtavarez

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
 - jekyll-paginate
 
paginate:         5
show_excerpts: true
