remote_theme: fongandrew/hydeout
markdown: kramdown
highlighter: rouge

title: "I'm David"
tagline: "Coding for fun and profit!"
url: https://davidtavarez.github.io/
description: "Software engineer, Security and privacy freak and Pentester enthusiast."

author:
  name: "David Tavarez"
  url: https://twitter.com/davidtavarez

plugins:
 - jekyll-feed
 - jekyll-gist
 - jekyll-paginate
 
paginate: 5
show_excerpts: true

version: 30

disqus:
  shortname: david-tavarezs-blog
